# Book settings. Learn more at https://jupyterbook.org/customize/config.html
title                     : CME 104 Python Workbook
author                    : Enze Chen and Vadim Khayms
copyright                 : "2025"
logo                      : assets/fig/icme-logo.png  # logo in top-left corner
exclude_patterns          : ["README.md", Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "**_solu.ipynb"]
only_build_toc_files      : true      # whether to ignore the extra files


#######################################################################################
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks       : cache
  timeout                 : 300       # max seconds for notebook to execute
  allow_errors            : true      # whether to allow and show errors


#######################################################################################
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button    : false     # button for users to edit page and submit a PR.
  use_issues_button       : true      # button for users to submit a GitHub issue
  use_repository_button   : false     # button for users to look at the source code in GitHub.
  home_page_in_navbar     : true      # include home page in the left Navigation Bar 
  use_multitoc_numbering  : true      # chapter numberings continue across sections
  baseurl                 : https://enze-chen.github.io/cme104-python   # The base URL where the book is hosted
  favicon                 : assets/fig/stanford-s.png      # the icon in the browser tab
  extra_footer            : |
    <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">
      <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" />
    </a>


#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : ""  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : false  # Add a thebe button to pages 
  colab_url                 : "https://colab.research.google.com" 
  deepnote_url              : "" 

repository:
  url                       : https://github.com/enze-chen/cme104-python  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links


#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. 
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes        : [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context


#######################################################################################
# Define the name of the latex output file for PDF builds
latex:
  latex_engine            : pdflatex
  latex_documents:
    targetname            : book.tex
bibtex_bibfiles           : ["assets/references.bib"]


#######################################################################################
# Other
sphinx:
  config:
    language              : en   # include explicitly for accessibility
    html_extra_path       : ["assets"]
    html_js_files         : https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    mathjax_path          : https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    bibtex_default_style  : plain 
    suppress_warnings     : ["mystnb.unknown_mime_type"]